### ISSUE TITLE
Add option to strip \n from strings?

### ISSUE THREAD

**Issue by Cyb0rk** [tristanls/logly#5]
Hi there,

do you still maintain logly? I use it very often and looking for an option to remove all \n newlines from the strings I log. Could you implement this to logly?

**Comment by tristanls** [comment]
Hi,

You can now do string processing as of v1.4.0: https://github.com/tristanls/logly#processors

**Comment by Cyb0rk** [comment]
Wow. Thanks a lot for your support!

**Comment by tristanls** [comment]
:smile:
